[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "target.*.dependencies",
  "workspace.dependencies",
]
[rule.formatting]
reorder_keys = true
