[package]
name = "zk-sca-verifier"
version = "0.2.0"
edition = "2024"

[dependencies]
risc0-zkvm = "~2.3"
zk-sca-guest-abi = { path = "../guest-abi" }
zk-sca-types = { path = "../types" }

[dev-dependencies]
bincode = "1.3"
hex = "0.4"
